version: "3.8"

services:
    ####Eye-Beacon: Version 1 -- Web Service#####
    web-service:
        container_name: "web-service"
        image: "eye-beacon/web-service:1.0.0"
        restart: always
        stdin_open: true
        tty: true
        command: -u 0.0.0.0 -p 5001
        ports:
                - "5001:5001"
        depends_on: 
                - redis

    ####Redis#####
    redis:
        container_name: "redis"
        image: redis:alpine
        restart: always
        volumes:
                - ./.docker/redis/data:/data
        command: redis-server
        ports:
                - "6379:6379"